{{- if .Values.typha.enabled -}}
{{- /* Make certs generated automatically last 100 years. Why? We're doing this automatically for customers
       who haven't provided their own certificates, meaning they might be blissfully unaware that these certs
       are even in use. If we put it at a "recommended" value like 1 year, there is a reasonable chance that
       a year from when they install, they will not have reissued a new cert, and they will have an outage. That's
       really bad. */ -}}
{{- $typhaca := genCA "typha-ca" 36500 -}}
{{- $typhacert := genSignedCert .Values.typha.tls.typhaCommonName (list ) (list .Values.typha.tls.typhaCommonName) 36500 $typhaca -}}
{{- $felixcert := genSignedCert .Values.typha.tls.felixCommonName (list ) (list .Values.typha.tls.felixCommonName) 36500 $typhaca -}}

# This manifest creates a Secret which contains the TLS key and certificate used by Typha to
# identify itself to Felix and encrypt communications

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-typha-certs
  namespace: kube-system
data:
{{- if include "calico.typha.tls" . }}
  typha.crt: {{ template "calico.maybeBase64Encode" .Values.typha.tls.typhaCrt }}
  typha.key: {{ template "calico.maybeBase64Encode" .Values.typha.tls.typhaKey }}
{{- else }}
  typha.crt: {{ $typhacert.Cert | b64enc }}
  typha.key: {{ $typhacert.Key | b64enc }}
{{- end }}

---

# This manifest creates a Secret which contains the TLS key and certificate used by Felix to
# identify itself to Typha and encrypt communications

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-felix-certs
  namespace: kube-system
data:
{{- if include "calico.typha.tls" . }}
  felix.crt: {{ template "calico.maybeBase64Encode" .Values.typha.tls.felixCrt }}
  felix.key: {{ template "calico.maybeBase64Encode" .Values.typha.tls.felixKey }}
{{- else }}
  felix.crt: {{ $felixcert.Cert | b64enc }}
  felix.key: {{ $felixcert.Key | b64enc }}
{{- end }}

---

# This manifest creates a ConfigMap which contains the certificate from the certificate authority
# used to create the Typha and Felix TLS certificates above.

apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-typha-ca
  namespace: kube-system
data:
{{- if include "calico.typha.tls" . }}
  caBundle: |
{{ .Values.typha.tls.caBundle | indent 4 }}
{{- else }}
  # This CA bundle is from a self-signed certificate authority autogenerated by Helm install.
  # Note that the CA key is not persisted anywhere, and so the certificate authority cannot be
  # used to generate additional certificates. Best practice is to rotate your TLS certificates
  # periodically, and for this you should generate a new certificate authority and retain the key.
  caBundle: |
{{ $typhaca.Cert | indent 4 }}
{{- end }}

{{- end -}}
