{{- if .Values.bgp }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: bgp-templates
  namespace: kube-system
data:
{{- range $key, $value := .Values.bgp }}
{{ $key | indent 2 }}: |
{{ $value | indent 4 }}
{{- end }}
{{- end }}
